services:
  mmm_serverpod:
    build: $PWD
    container_name: mmm_serverpod
    restart: unless-stopped
    expose:
      - "8080"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mmm_serverpod

volumes:
  caddy_data:
  caddy_config:

