name: movie_match
description: "Pick your favourite movies for the evening"

publish_to: "none"

version: 1.0.0+1

platforms:
  web:
  android:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  flutter_svg: ^2.0.17
  mmm_client:
    path: ../mmm_client
  salute_handler:
    path: ../mmm_plugin
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  qr_flutter: ^4.1.0
  flutter_card_swiper: ^7.0.2
  flutter_confetti: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "0xFF723523"
    theme_color: "0xFF35211C"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: false

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts\Montserrat-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts\Montserrat-VariableFont_wght.ttf

  assets:
    - assets/logo.svg
    - assets/unknown.png
    - assets/logo_with_text.svg
    - assets/number_one.svg
    - assets/number_three.svg
    - assets/number_two.svg
