name: mmm
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  flutter_svg: ^2.0.17
  mmm_client:
    path: ../mmm_client
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  qr_flutter: ^4.1.0
  flutter_card_swiper: ^7.0.2
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts\Montserrat-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts\Montserrat-VariableFont_wght.ttf

  assets:
    - assets/logotype.svg
    - assets/pine_trees.jpg
